### ISSUE TITLE
Included in reference list

### ISSUE THREAD

**Issue by amis92** [davidwengier/SourceGeneratorTemplate#3]
Hi,

I've included your repository in my personal [C# Source Generators list](https://github.com/amis92/csharp-source-generators) to help gather these kind of projects in one place and hopefully under single umbrella, thus I propose to add the `csharp-sourcegenerator` topic to this repository to help with visibility.

I hope you're okay with this. If you happen to know other generator projects, I'll be happy to enlist those in my list as well.

Thanks!

**Comment by davidwengier** [comment]
Sure thing. I've also added it to https://github.com/davidwengier/SourceGeneratorPlayground which is the source for https://sourcegen.dev which you also might be interested in.

**Comment by amis92** [comment]
Added to my list as well, thanks!
