### ISSUE TITLE
IncrementalGenerator is not working correctly.

### ISSUE THREAD

**Issue by AvtsVivek** [davidwengier/SourceGeneratorTemplate#8]
Hi Thanks for this simple tutorial.

The moment I add a new type to Program.cs, the IncrementalGenerator stopped working. The other generator is working fine.

```cs
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Types in this assembly:");
        foreach (Type t in typeof(Program).Assembly.GetTypes())
        {
            Console.WriteLine(t.FullName);
        }
    }
}

public class HereWeGo {  }
```

![image](https://user-images.githubusercontent.com/41255281/160268974-713fe1be-1951-45c6-9b0e-2fec2b4b6752.png)

![image](https://user-images.githubusercontent.com/41255281/160268998-63ec90f7-3d44-4767-a63c-4941d6e5a66c.png)

If I then comment out that HereWeGo class, restart visual studio, then things restore back.

**Comment by davidwengier** [comment]
Thanks. I should test my work next time :)
